FORMAT: 1A
HOST: http://twentyapi-demo.gssdev.xyz/api/v1

# TwentyAPI - Document

**Root URL** `http://twentyapi-demo.gssdev.xyz/api/v1`

<!-- include(parts/intro.md) -->

<!-- include(parts/group-auth.md) -->

<!-- include(parts/group-properties.md) -->

